<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<style>body{background:white;}

/* Mobile CSS*/
@media only screen and (max-width: 768px) {

#navbar-toggler {
    display: block !important;
}
.navbar-dark .navbar-brand {
    margin-left: 1%;
}
}
</style>
<div align="left">
<div class="header-st mb-4">
<div class="container">
<div class="row">
<h3>FAQ</h3>
</div>
</div>
</div>
</div>
</div>

<div style="margin-top:35px">
					
						<h3><?php echo lang('core menu terms'); ?></h3>
					</div>
				</div>
			</div>
</div>

<div class="container theme-showcase" role="main">
	
	<div class="row">
		<div class="col-md-12">


<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to create ORIXPAY account?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; text-align:start; -webkit-text-stroke-width:0px"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Visit&nbsp;<a href="https://www.orixpay.com/" style="box-sizing:border-box; color:#428bca; text-decoration:none">https://www.orixpay.com</a>, click on <a href="https://www.orixpay.com/user/register">Create account</a> button&nbsp;and complete the required form.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; text-align:start; -webkit-text-stroke-width:0px">&nbsp;</p>

<p style="margin:0px 0px 10px; text-align:start; -webkit-text-stroke-width:0px"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to withdraw from ORIXPAY account?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">As new user, your account will have &ldquo;Initial Verification&rdquo; status with limitations. You can deposit the money in Initial Verification&nbsp;status, but cannot withdraw. You need to follow the links <em>Account setting &gt; Verification</em> then You will have to submit your personal details and some documents for Identity Verification. After evaluation of required documents, your account will be verified within 24 hours on &quot;</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span>Extended verification&quot; status<span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">. Afterwards, you will enjoy full services of OrixPay.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to integrate ORIXPAY with your business website?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">For this purpose, you have to upgrade your verified account to &quot;</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span>Extended verification&quot;<span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"> status. After upgradation&nbsp;you can integrate your website with OrixPay Payment Services through its API and also will be abled to create your own store with in the user account.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: What is way of depositing money? How long it will take to transfer the money to OrixPay account?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">After login, you will see Deposit button in top cover of Dashboard. By clicking the button, you will have a variety of payment methods. All amounts exapt Payoneer and OrioCard would automatically be transferred to your account.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: What is mode of deposit through&nbsp;<span class="SpellE" style="box-sizing:border-box">Payoneer</span>, Orio Card?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">By opting any option out of these two, you will put the desired amount and send a request. Subsequently, you will get details while requesting desposit.&nbsp;You will need to follow the on screen instructions,&nbsp;after necessary verification, your payment would be credited.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to withdraw the amount?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">First of all, login your account complete the billing profile by following the links <em>Account Setting &gt; Billing setting</em>&nbsp;then click on Withdraw option in dashboard. Put the amount, select the desire option and click <em>Send money</em> button. Within the time frame, payment would be sent to your account.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: What are the charges of depositing and withdrawing money?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Every method has different service charges.&nbsp;<a href="https://www.orixpay.com/instructions" style="box-sizing:border-box; color:#428bca; text-decoration:none">click here for fee structure</a></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to transfer the money?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Primarily, you need to know the OrixPay account of receiver. After that you can transfer the money by clicking on the menu &quot;<em>Money Transfer</em>&quot; and putting the amount, mention the Account ID and amount then&nbsp;click on &quot;<em>Send money&quot;</em> button.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: Is there any money transfer charges?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">No. There are no charges for money transfers.&nbsp;<a href="https://www.orixpay.com/instructions" style="box-sizing:border-box; color:#428bca; text-decoration:none">click here for fee structure</a></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to use Currency Exchange option?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">You can exchange your base currency i.e. USD in AED, SAR, EUR, GBP, PKR, etc. We are also working on addition of new currencies.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to check the balance other than base currency USD?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">In Dashboard, hover mouse pointer to Info icon. Info icon available besides base currency USD.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: Can I forward Digital Invoice through OrixPay to my client so that he/she could send me payment according to invoice?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Yes. There is an option in your account &ldquo;<em>Invoice</em>&rdquo;. By using it, you can send Payment Invoice to the OrixPay user. There is not fee applicable for invoicing.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: What is meant by Voucher in Dashboard?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">E-voucher feature is introduced for non-OrixPay users. You can prepare E-voucher of any amount and send it to non-OrixPay user through email. He / she can create OrixPay account in 30 seconds and deposit the E-voucher in his / her account. E-voucher can be prepared in 6 different currencies.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: Is there any fee for creation of E-voucher?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">No, there is not fee applicable for E-voucher.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: What is &lsquo;Orio Card&rsquo;?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Orio Card is Visa Debit Card. You can shop online from millions of online stores through with almost unlimited number of transactions.&nbsp;You can pay to those online stores which have accepted Visa.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: Can I use OrioCard in ATM &amp; POS?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Yes. It can be used on millions of POS and ATM&rsquo;s where Master Card accepted.&nbsp;<a href="https://www.orixpay.com/instructions" style="box-sizing:border-box; color:#428bca; text-decoration:none">click here</a>&nbsp;to see transaction fesses and card limitations.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to get OrioCard?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Go to the side menu &quot;<em>Shops &amp; Payments&quot;</em>, Find <em>&quot;OrixPay Offical Store&quot;&nbsp;</em>and then purchase OrioCard visa debit card for two years of expiry. Remember while shopping from any store for anything, the payment will deduct straight away from your OrixPay account.&nbsp;After getting your request your Orio Card will be forwarded through courier service to your registered verified postal address.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: Is there any charges for getting OrioCard?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Yes, $35 would be deducted from your account when you will place the order for OrioCard.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to recharge balance in OrioCard?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Go to Dashboard, click on Withdraw option and select OrioCard method to recharge your card. Enter desired amount click <em>&quot;Send Money&quot; </em>button. Amount would be transferred to your card within the time frame.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to get the details of all my transactions?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">In Dashboard, click on <em>&quot;Transactions&quot;</em>.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: Is there any way of recovering the amount in case of inaccuracy in transaction(s) or any dispute with other user?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">OrixPay provides complete dispute management system. You can create dispute in case of anything happened undesirably. In case you win the dispute, amount would be refunded to your account from 2<sup style="box-sizing:border-box; font-size:10.5px; line-height:0; position:relative; vertical-align:baseline; top:-0.5em">nd</sup>&nbsp;party&rsquo;s account.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: How to get Support of OrixPay team?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Click on <em>&quot;Support&quot;</em> button available in dashboard and write down your issue. You would be replied accordingly in 24 hours through Open Ticket. No emails would be entertained.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify">&nbsp;</p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial"><b style="box-sizing:border-box; font-weight:bold">Q: If I am not ORIXPAY user, then how I can get Support?</b></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="margin:0px 0px 10px; -webkit-text-stroke-width:0px; text-align:justify"><span style="font-size:14px"><span style="box-sizing:border-box"><span style="color:#333333"><span style="font-family:&quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif"><span style="font-style:normal"><span style="font-variant-ligatures:normal"><span style="font-variant-caps:normal"><span style="font-weight:400"><span style="letter-spacing:normal"><span style="orphans:2"><span style="text-transform:none"><span style="white-space:normal"><span style="widows:2"><span style="word-spacing:0px"><span style="background-color:#ffffff"><span style="text-decoration-style:initial"><span style="text-decoration-color:initial">Go to&nbsp;<a href="https://www.orixpay.com/" style="box-sizing:border-box; color:#428bca; text-decoration:none">https://www.orixpay.com</a>&nbsp;and click on contact. Our team will respond you in 24 &ndash; 48 hours through email.</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>
</div>
</div>
</div>
</div>

<div style="margin-bottom:35px">

<?php echo $content; ?>